spring:
  application:
    name: aviation-api

logging:
  level:
    root: INFO
    com.aviation.api: DEBUG

server:
  servlet:
    context-path: /api

aviation:
  weather:
    api:
      base-url: https://aviationweather.gov/api/data
      max-attempts: 3
      initial-interval: 1000
      multiplier: 2.0
      max-interval: 10000
